# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_main.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QHeaderView, QLabel,
    QLayout, QLineEdit, QListWidget, QListWidgetItem,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTableWidget, QTableWidgetItem, QVBoxLayout,
    QWidget)
import recursos_grafics_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 610)
        MainWindow.setIconSize(QSize(34, 34))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.filter1_label = QLabel(self.centralwidget)
        self.filter1_label.setObjectName(u"filter1_label")
        self.filter1_label.setGeometry(QRect(20, 10, 121, 16))
        self.filter1_listWidget = QListWidget(self.centralwidget)
        self.filter1_listWidget.setObjectName(u"filter1_listWidget")
        self.filter1_listWidget.setGeometry(QRect(20, 50, 121, 161))
        self.tableWidget = QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(20, 320, 761, 251))
        self.datasheetButton = QPushButton(self.centralwidget)
        self.datasheetButton.setObjectName(u"datasheetButton")
        self.datasheetButton.setGeometry(QRect(740, 270, 41, 41))
        font = QFont()
        font.setPointSize(18)
        self.datasheetButton.setFont(font)
        icon = QIcon()
        icon.addFile(u":/logos/link_34dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.datasheetButton.setIcon(icon)
        self.datasheetButton.setIconSize(QSize(34, 34))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(580, 270, 41, 41))
        font1 = QFont()
        font1.setPointSize(20)
        self.label_2.setFont(font1)
        self.label_2.setPixmap(QPixmap(u":/logos/archive_34dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.svg"))
        self.filter1_lineEdit = QLineEdit(self.centralwidget)
        self.filter1_lineEdit.setObjectName(u"filter1_lineEdit")
        self.filter1_lineEdit.setGeometry(QRect(20, 30, 121, 21))
        self.filter2_lineEdit = QLineEdit(self.centralwidget)
        self.filter2_lineEdit.setObjectName(u"filter2_lineEdit")
        self.filter2_lineEdit.setGeometry(QRect(160, 30, 121, 21))
        self.filter2_listWidget = QListWidget(self.centralwidget)
        self.filter2_listWidget.setObjectName(u"filter2_listWidget")
        self.filter2_listWidget.setGeometry(QRect(160, 50, 121, 161))
        self.filter2_label = QLabel(self.centralwidget)
        self.filter2_label.setObjectName(u"filter2_label")
        self.filter2_label.setGeometry(QRect(160, 10, 121, 16))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(330, 270, 31, 41))
        self.filterG_lineEdit = QLineEdit(self.centralwidget)
        self.filterG_lineEdit.setObjectName(u"filterG_lineEdit")
        self.filterG_lineEdit.setGeometry(QRect(20, 290, 121, 21))
        self.filter1_pushButton = QPushButton(self.centralwidget)
        self.filter1_pushButton.setObjectName(u"filter1_pushButton")
        self.filter1_pushButton.setGeometry(QRect(20, 210, 121, 24))
        font2 = QFont()
        font2.setPointSize(8)
        self.filter1_pushButton.setFont(font2)
        self.filter2_pushButton = QPushButton(self.centralwidget)
        self.filter2_pushButton.setObjectName(u"filter2_pushButton")
        self.filter2_pushButton.setGeometry(QRect(160, 210, 121, 24))
        self.stock_text = QLineEdit(self.centralwidget)
        self.stock_text.setObjectName(u"stock_text")
        self.stock_text.setGeometry(QRect(620, 270, 61, 41))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(740, 10, 41, 41))
        self.pushButton_4.setFont(font)
        icon1 = QIcon()
        icon1.addFile(u":/logos/file_open_34dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QSize(34, 34))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(690, 10, 41, 41))
        self.pushButton_5.setFont(font1)
        icon2 = QIcon()
        icon2.addFile(u":/logos/autorenew_34dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setIconSize(QSize(34, 34))
        self.FilterPN_lineEdit = QLineEdit(self.centralwidget)
        self.FilterPN_lineEdit.setObjectName(u"FilterPN_lineEdit")
        self.FilterPN_lineEdit.setGeometry(QRect(150, 290, 121, 21))
        self.FilterPN_label = QLabel(self.centralwidget)
        self.FilterPN_label.setObjectName(u"FilterPN_label")
        self.FilterPN_label.setGeometry(QRect(150, 260, 121, 31))
        self.filterG_label = QLabel(self.centralwidget)
        self.filterG_label.setObjectName(u"filterG_label")
        self.filterG_label.setGeometry(QRect(20, 260, 121, 31))
        self.listWidget_4 = QListWidget(self.centralwidget)
        self.listWidget_4.setObjectName(u"listWidget_4")
        self.listWidget_4.setGeometry(QRect(660, 80, 121, 131))
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(20, 240, 761, 31))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget = QWidget(self.widget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(9, 4, 741, 21))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetMinimumSize)

        self.verticalLayout.addLayout(self.horizontalLayout)

        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(290, 270, 41, 41))
        self.label_7.setFont(font1)
        self.label_7.setPixmap(QPixmap(u":/logos/content_paste_34dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.svg"))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(370, 270, 41, 41))
        self.label_8.setFont(font1)
        self.label_8.setPixmap(QPixmap(u":/logos/inventory_2_34dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.svg"))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(400, 270, 131, 41))
        self.filter3_listWidget = QListWidget(self.centralwidget)
        self.filter3_listWidget.setObjectName(u"filter3_listWidget")
        self.filter3_listWidget.setGeometry(QRect(300, 50, 121, 161))
        self.filter3_label = QLabel(self.centralwidget)
        self.filter3_label.setObjectName(u"filter3_label")
        self.filter3_label.setGeometry(QRect(300, 10, 121, 16))
        self.filter3_pushButton = QPushButton(self.centralwidget)
        self.filter3_pushButton.setObjectName(u"filter3_pushButton")
        self.filter3_pushButton.setGeometry(QRect(300, 210, 121, 24))
        self.filter3_lineEdit = QLineEdit(self.centralwidget)
        self.filter3_lineEdit.setObjectName(u"filter3_lineEdit")
        self.filter3_lineEdit.setGeometry(QRect(300, 30, 121, 21))
        self.filter4_listWidget = QListWidget(self.centralwidget)
        self.filter4_listWidget.setObjectName(u"filter4_listWidget")
        self.filter4_listWidget.setGeometry(QRect(440, 50, 121, 161))
        self.filter4_label = QLabel(self.centralwidget)
        self.filter4_label.setObjectName(u"filter4_label")
        self.filter4_label.setGeometry(QRect(440, 10, 121, 16))
        self.filter4_pushButton = QPushButton(self.centralwidget)
        self.filter4_pushButton.setObjectName(u"filter4_pushButton")
        self.filter4_pushButton.setGeometry(QRect(440, 210, 121, 24))
        self.filter4_lineEdit = QLineEdit(self.centralwidget)
        self.filter4_lineEdit.setObjectName(u"filter4_lineEdit")
        self.filter4_lineEdit.setGeometry(QRect(440, 30, 121, 21))
        self.clear_all_pushButton = QPushButton(self.centralwidget)
        self.clear_all_pushButton.setObjectName(u"clear_all_pushButton")
        self.clear_all_pushButton.setGeometry(QRect(660, 220, 121, 23))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.filter1_label.setText(QCoreApplication.translate("MainWindow", u"Filter 1", None))
        self.datasheetButton.setText("")
        self.label_2.setText("")
        self.filter2_label.setText(QCoreApplication.translate("MainWindow", u"Filter 2", None))
        self.label_5.setText("")
        self.filter1_pushButton.setText(QCoreApplication.translate("MainWindow", u" reset", None))
        self.filter2_pushButton.setText(QCoreApplication.translate("MainWindow", u"reset", None))
        self.pushButton_4.setText("")
        self.pushButton_5.setText("")
        self.FilterPN_label.setText(QCoreApplication.translate("MainWindow", u"Filtre Manufacture PN", None))
        self.filterG_label.setText(QCoreApplication.translate("MainWindow", u"Filtre general", None))
        self.label_7.setText("")
        self.label_8.setText("")
        self.label_9.setText("")
        self.filter3_label.setText(QCoreApplication.translate("MainWindow", u"Filter 3", None))
        self.filter3_pushButton.setText(QCoreApplication.translate("MainWindow", u"reset", None))
        self.filter4_label.setText(QCoreApplication.translate("MainWindow", u"Filter 4", None))
        self.filter4_pushButton.setText(QCoreApplication.translate("MainWindow", u"reset", None))
        self.clear_all_pushButton.setText(QCoreApplication.translate("MainWindow", u"Reset all filters", None))
    # retranslateUi

